In [54]:
#Slide ke 6
mahasiswa = ["Ivan Wahyu Putratama", 2021071022, "Informatika", "Desain analisis ALgoritma", "14 september 2022", "Universitas Pembangunan Jaya"]
print(mahasiswa)

['Ivan Wahyu Putratama', 2021071022, 'Informatika', 'Desain analisis ALgoritma', '14 september 2022', 'Universitas Pembangunan Jaya']


In [55]:
#Slide ke 7
bin_colors = ['Red','Green','Blue','Yellow']
bin_colors[0]

'Red'

In [56]:
# Slide ke 8
mahasiswa[1]

2021071022

In [57]:
# Slide ke 9
mahasiswa[5]

'Universitas Pembangunan Jaya'

In [58]:
#Slide ke 10
bin_colors[0:2]

['Red', 'Green']

In [59]:
#Slide ke 11
mahasiswa[1:3]

[2021071022, 'Informatika']

In [60]:
# Slide ke 12
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [61]:
# Slide ke 13
for aUpj in mahasiswa:
  print(" UPJ " , aUpj)

 UPJ  Ivan Wahyu Putratama
 UPJ  2021071022
 UPJ  Informatika
 UPJ  Desain analisis ALgoritma
 UPJ  14 september 2022
 UPJ  Universitas Pembangunan Jaya


In [62]:
# Slide ke 14
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[2:]

('Blue', 'Yellow')

In [63]:
bin_colors[:2]

('Red', 'Green')

In [64]:
#Slide ke 15
UPJ=('Universitas', 'Pembangunan', 'Jaya')
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [65]:
# Slide ke 16
nested_tuple =(100, (200, 400, 600), 300, (400, 800))
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [66]:
nested_tuple[2]

300

In [67]:
# Slide ke 17
bin_colors={
    "manual_color":"Yellow",
    "approved_color":"Green",
    "refused_color":"Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [68]:
 # Slide ke 18
 bin_colors.get('approved_color')

'Green'

In [69]:
bin_colors['approved_color']

'Green'

In [70]:
# Slide ke 19
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [71]:
# Slide ke 20
dataMahasiswa={
    "Nama":"Ivan Wahyu Putratama",
    "NIM":"2021071022",
    "Prodi":"Informatika",
    "Universitas":"UPJ"
}
print(dataMahasiswa)

{'Nama': 'Ivan Wahyu Putratama', 'NIM': '2021071022', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [72]:
# Slide ke 21
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [73]:
# Slide ke 22
red = {'strawberry', 'rose','rose'}
print(red)

{'rose', 'strawberry'}


In [74]:
# Slide ke 23
yellow = {'dandelions', 'leaves', 'fire hydrant'}
red = {'rose', 'blood', 'leaves', 'fire hydrant'}
yellow|red

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [75]:
yellow = {'dandelions', 'leaves', 'fire hydrant'}
red = {'rose', 'blood', 'leaves', 'fire hydrant'}
yellow&red

{'fire hydrant', 'leaves'}

In [76]:
# Slide ke 24
import pandas as pd
df = pd.DataFrame([
  ['1', 'Fares', 32, True],
  ['2', 'Elena', 23, False],
  ['3', 'Steven', 40, True]])
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [77]:
# Slide ke 25
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [78]:
# Slide ke 26
# Seleksi kolom
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [79]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [80]:
# Slide ke 27
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [81]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [82]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [83]:
# Slide ke 28
import pandas as pd
df = pd.DataFrame([
  ['Informatika', 50, 30, 20],
  ['Sistem Informasi', 55, 30, 25],
  ['Teknik Sipil', 40, 30, 10]])
df

0   1   2   3
0       Informatika  50  30  20
1  Sistem Informasi  55  30  25
2      Teknik Sipil  40  30  10

In [84]:
df.columns = ['Prodi', 'Mahasiswa', 'Laki laki', 'Perempuan']
df

Prodi  Mahasiswa  Laki laki  Perempuan
0       Informatika         50         30         20
1  Sistem Informasi         55         30         25
2      Teknik Sipil         40         30         10

In [85]:
# Slide ke 29
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [86]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [87]:
# Slide ke 30
import numpy as np
myMatrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [88]:
# Slide ke 32
myVector = [22,33,44,55]
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [89]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [90]:
# Slide ke 34
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item): 
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.items)

In [91]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

In [92]:
stack.pop()

'Yellow'

In [93]:
stack.isEmpty()

False

In [94]:
# Slide ke 36
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [95]:
queue = Queue()

In [96]:
queue.enqueue('Red')

In [97]:
queue.enqueue('Green')

In [98]:
queue.enqueue('Blue')

In [99]:
queue.enqueue('Yellow')

In [100]:
print(queue.size())

4


In [101]:
print(queue.dequeue())

Red


In [102]:
print(queue.dequeue())

Green
